#Undertow
server:
  undertow:
    io-threads: 4
    worker-threads: 20
    buffer-size: 1024
    direct-buffers: true

spring:
  application:
    name: eureka-server
  profiles:
    active: dev
  security:
    basic:
      enable: true
    user:
      name: eugene
      password: eugene
