server:
  port: 10001

eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    # 不在注册中心注册自己
    register-with-eureka: false
    # 表示自己就是注册中心，不需要检索服务，只需要维护服务实例
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer1:10000/eureka/
